eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: user-api
  datasource:
    password: '12345'
    username: root
    url: jdbc:mysql://localhost:3306/mydb
server:
  error:
    include-stacktrace: never
    include-exception: 'false'
  port: ${PORT:0}
